package sistemafarmaciaGUI;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sistemafarmacia.ComunicacionBD;


public class frmAgregarUsuario extends javax.swing.JDialog {        
    
    private static final String tabla = "usuarios";
    private static final String[] datosTabla = new String [] {"id","tipo_usuario", "usuario", "contrasena" } ;

    
    String[] empleados;
    JTable tblUsuarios;
    boolean edicion = false;
    
    public frmAgregarUsuario(java.awt.Dialog parent, boolean modal, String[] empleados, JTable tblUsuarios) {
        super(parent, modal);
        initComponents();
        
        this.edicion = true;
        this.tblUsuarios = tblUsuarios;
        this.empleados = empleados;
                                             
        txtUsuario.setText(empleados[2]);
        txtContraseña.setText(empleados[3]);
        
        if(empleados[1].equals("administrador")){
            jrbTipoUsuario2.setSelected(true);
        }
        else
          jrbTipoUsuario1.setSelected(true);
    }
    
    public frmAgregarUsuario(java.awt.Dialog parent, boolean modal, JTable tblUsuarios) {
        super(parent, modal);
        initComponents();
        
        this.tblUsuarios = tblUsuarios;
        
        
        
        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarios = new javax.swing.ButtonGroup();
        panFondo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        panSalir = new javax.swing.JPanel();
        lblSalir = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        jrbTipoUsuario1 = new javax.swing.JRadioButton();
        jrbTipoUsuario2 = new javax.swing.JRadioButton();
        txtUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panFondo.setBackground(new java.awt.Color(255, 255, 255));
        panFondo.setMinimumSize(new java.awt.Dimension(500, 500));
        panFondo.setPreferredSize(new java.awt.Dimension(500, 500));
        panFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblTitulo.setText("Agregar Usuario");
        panFondo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblUsuario.setText("Usuario:");
        panFondo.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblContraseña.setText("Contraseña:");
        panFondo.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        lblTipo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblTipo.setText("Tipo de usuario:");
        panFondo.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 20));

        btnCancelar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        panFondo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, 30));

        btnAceptar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        panFondo.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, 30));

        panSalir.setBackground(new java.awt.Color(255, 255, 255));

        lblSalir.setBackground(new java.awt.Color(255, 255, 255));
        lblSalir.setFont(new java.awt.Font("Roboto", 0, 33)); // NOI18N
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("x");
        lblSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panSalirLayout = new javax.swing.GroupLayout(panSalir);
        panSalir.setLayout(panSalirLayout);
        panSalirLayout.setHorizontalGroup(
            panSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        panSalirLayout.setVerticalGroup(
            panSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panFondo.add(panSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 40));

        txtContraseña.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        panFondo.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 220, 30));

        usuarios.add(jrbTipoUsuario1);
        jrbTipoUsuario1.setText("Empleado");
        jrbTipoUsuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbTipoUsuario1MouseClicked(evt);
            }
        });
        jrbTipoUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTipoUsuario1ActionPerformed(evt);
            }
        });
        panFondo.add(jrbTipoUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 120, 30));

        usuarios.add(jrbTipoUsuario2);
        jrbTipoUsuario2.setText("Administrador");
        jrbTipoUsuario2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbTipoUsuario2MouseClicked(evt);
            }
        });
        panFondo.add(jrbTipoUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 120, 30));

        txtUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        panFondo.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        dispose();
    }//GEN-LAST:event_lblSalirMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
                         
        String tipo = "";
        String user = "";
        String pass = "";
        
        if( txtUsuario.getText().length() == 0 ) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un nombre de usuario.",
                    "Validación",
                    JOptionPane.ERROR_MESSAGE);
            txtUsuario.requestFocus();
            return;
        }else {
            user = txtUsuario.getText();
                                   
        }
        if( txtContraseña.getText().length() == 0 ) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese una contraseña.",
                    "Validación",
                    JOptionPane.ERROR_MESSAGE);
            txtContraseña.requestFocus();
            return;
        }else {
            pass = txtContraseña.getText();
                                    
        }                
                    
        if(jrbTipoUsuario1.isSelected()) {
            tipo = "empleado";
        }else if(jrbTipoUsuario2.isSelected()) {
            tipo = "administrador";            
        }else {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un tipo de usuario.",
                    "Validación",
                    JOptionPane.ERROR_MESSAGE);   
            return;
        }
           
        String[] subir = {tipo,user,pass};
        try {
         
            if(edicion == true){
            
            ComunicacionBD.actualizarBD(tabla, subir, empleados[0]);
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "¡Empleado editado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            }
            else{
               ComunicacionBD.subirBD(tabla, subir);
               javax.swing.JOptionPane.showMessageDialog(this, 
                    "¡Empleado agregado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            
            btnCancelarMouseClicked(evt);
            tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
                            ComunicacionBD.datosBD(tabla),datosTabla));
            
        } catch (SQLException ex) {
            Logger.getLogger(frmTablaPedidos.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        lblSalirMouseClicked(evt);
        
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
        panSalir.setBackground(Color.red);
        lblSalir.setForeground(Color.white);
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        panSalir.setBackground(Color.white);
        lblSalir.setForeground(Color.black);
    }//GEN-LAST:event_lblSalirMouseExited

    private void jrbTipoUsuario1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbTipoUsuario1MouseClicked

    }//GEN-LAST:event_jrbTipoUsuario1MouseClicked

    private void jrbTipoUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTipoUsuario1ActionPerformed

    }//GEN-LAST:event_jrbTipoUsuario1ActionPerformed

    private void jrbTipoUsuario2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbTipoUsuario2MouseClicked

    }//GEN-LAST:event_jrbTipoUsuario2MouseClicked

           
    /**
     * @param args the command line arguments
    */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList datosPedido = null;
                frmDatos dialog = new frmDatos(new javax.swing.JFrame(), true, ArrayList datosPedido);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        //</editor-fold>

        /* Create and display the dialog 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList datosPedido = null;
                frmDatos dialog = new frmDatos(new javax.swing.JFrame(), true, ArrayList datosPedido);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        //</editor-fold>

        /* Create and display the dialog 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList datosPedido = null;
                frmDatos dialog = new frmDatos(new javax.swing.JFrame(), true, ArrayList datosPedido);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        //</editor-fold>

        /* Create and display the dialog 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList datosPedido = null;
                frmDatos dialog = new frmDatos(new javax.swing.JFrame(), true, ArrayList datosPedido);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JRadioButton jrbTipoUsuario1;
    private javax.swing.JRadioButton jrbTipoUsuario2;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panFondo;
    private javax.swing.JPanel panSalir;
    public javax.swing.JTextField txtContraseña;
    public javax.swing.JTextField txtUsuario;
    private javax.swing.ButtonGroup usuarios;
    // End of variables declaration//GEN-END:variables
}
