package sistemafarmaciaGUI;

import java.awt.Color;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sistemafarmacia.ComunicacionBD;
import sistemafarmacia.Conexion;
import sistemafarmacia.Pedidos;
import sistemafarmaciaGUI.frmPedido;

public class frmModificar extends javax.swing.JDialog {        
    
    private static final String tabla = "pedidos";
    private static final String[] datosTabla = new String [] {"id","Producto", "Tipo", "Cantidad", "Proveedor","Sucursal" } ;
    frmPedido pedido;
    Pedidos objPedido;
    String[] pedidos;
    JTable tblPedidos;

    public frmModificar(java.awt.Dialog parent, boolean modal, String[] pedido, JTable tblPedidos) {
        super(parent, modal);
        initComponents();
        
        this.tblPedidos = tblPedidos;
        this.pedidos = pedido;
        
        
        
        txtProducto.setText(pedidos[1]);
        cmbTipo.setSelectedItem(pedidos[2]);
        txtCantidad.setText(pedidos[3]);
        
        if(pedidos[4].equals("Medley"))
            jrbProveedor1.setSelected(true);
        else
            jrbProveedor2.setSelected(true);;
        
        if(pedidos[5].equals("Las Palmas"))
            cbxSucursal1.setSelected(true); 
        else
            cbxSucursal2.setSelected(true);
        
        
                                                                          
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proveedores = new javax.swing.ButtonGroup();
        sucursales = new javax.swing.ButtonGroup();
        panFondo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        lblSucursal = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        panSalir = new javax.swing.JPanel();
        lblSalir = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        txtProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jrbProveedor1 = new javax.swing.JRadioButton();
        jrbProveedor2 = new javax.swing.JRadioButton();
        cbxSucursal1 = new javax.swing.JCheckBox();
        cbxSucursal2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 500));

        panFondo.setBackground(new java.awt.Color(255, 255, 255));
        panFondo.setMinimumSize(new java.awt.Dimension(500, 500));
        panFondo.setPreferredSize(new java.awt.Dimension(500, 500));
        panFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblTitulo.setText("Modificar Pedido");
        panFondo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        lblProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblProducto.setText("Producto:");
        panFondo.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lblTipo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblTipo.setText("Tipo:");
        panFondo.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblCantidad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblCantidad.setText("Cantidad:");
        panFondo.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        lblProveedor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblProveedor.setText("Proveedor:");
        panFondo.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 20));

        lblSucursal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblSucursal.setText("Sucursal:");
        panFondo.add(lblSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        panFondo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, 30));

        btnAceptar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        panFondo.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, 30));

        lblSalir.setFont(new java.awt.Font("Roboto", 0, 33)); // NOI18N
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("x");
        lblSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panSalirLayout = new javax.swing.GroupLayout(panSalir);
        panSalir.setLayout(panSalirLayout);
        panSalirLayout.setHorizontalGroup(
            panSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        panSalirLayout.setVerticalGroup(
            panSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panFondo.add(panSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 40));

        cmbTipo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona uno", "Tabletas", "Capsulas", "Solución", "Inyectable" }));
        panFondo.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 220, 30));
        panFondo.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 220, 30));

        txtCantidad.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        panFondo.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 90, 30));

        proveedores.add(jrbProveedor1);
        jrbProveedor1.setText("Medley");
        jrbProveedor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbProveedor1MouseClicked(evt);
            }
        });
        jrbProveedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbProveedor1ActionPerformed(evt);
            }
        });
        panFondo.add(jrbProveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 30));

        proveedores.add(jrbProveedor2);
        jrbProveedor2.setText("Biomep");
        jrbProveedor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbProveedor2MouseClicked(evt);
            }
        });
        panFondo.add(jrbProveedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 120, 30));

        sucursales.add(cbxSucursal1);
        cbxSucursal1.setText("Las Palmas");
        panFondo.add(cbxSucursal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 120, 30));

        sucursales.add(cbxSucursal2);
        cbxSucursal2.setText("Puerto México");
        panFondo.add(cbxSucursal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        dispose();
    }//GEN-LAST:event_lblSalirMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
       
        
        
        
        
        Pedidos objPedido = new Pedidos();
        
        
        
        if( txtProducto.getText().length() == 0 ) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese nombre del producto.",
                    "Validación",
                    JOptionPane.ERROR_MESSAGE);
            txtProducto.requestFocus();
            return;
        }else {
            String producto = txtProducto.getText();
            objPedido.setNombreProducto(producto);            
        }                
        
        if( (String)cmbTipo.getSelectedItem() == "Selecciona uno" ) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un tipo de producto.",
                    "Validación",
                    JOptionPane.ERROR_MESSAGE);
            cmbTipo.requestFocus();
            return;
        }else {
            try {
                String tipo = (String)cmbTipo.getSelectedItem();
                objPedido.setTipoProducto(tipo);
            } catch (Exception ex) {
                Logger.getLogger(frmPedido.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if( txtCantidad.getText().length() == 0  ) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese una cantidad.",
                    "Validación",
                    JOptionPane.ERROR_MESSAGE);
            txtCantidad.requestFocus();
            return;
        }else {
            try {
                int cantidad = Integer.parseInt(txtCantidad.getText());
                objPedido.setCantidad(cantidad); 
            }catch(NumberFormatException ex) {
                JOptionPane.showMessageDialog(
                    this,
                    "Ingrese una cantidad válida.",
                    "Validación",
                    JOptionPane.ERROR_MESSAGE);
                txtCantidad.requestFocus();
                return;
            }
                       
        }
        
        if(jrbProveedor1.isSelected()) {
            objPedido.setProveedor("Medley");
        }else if(jrbProveedor2.isSelected()) {
            objPedido.setProveedor("Biomep");            
        }else {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un proveedor.",
                    "Validación",
                    JOptionPane.ERROR_MESSAGE);   
            return;
        }
                
        if(cbxSucursal1.isSelected()) {
            objPedido.setSucursal("Las Palmas");
        }else if(cbxSucursal2.isSelected()) {
            objPedido.setSucursal("Puerto México");
        }else {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una sucursal.",
                    "Validación",
                    JOptionPane.ERROR_MESSAGE);    
            return;
        }
        
        
        try {
           Conexion objConexion = new Conexion();                                       
        
            String[] subir = {objPedido.getNombreProducto(),objPedido.getTipoProducto(),String.valueOf(objPedido.getCantidad()),objPedido.getProveedor(),objPedido.getSucursal()};
            ComunicacionBD.actualizarBD(tabla, subir, pedidos[0]);
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "¡Pedido editado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            btnCancelarMouseClicked(evt);
            
            
           /* frmTablaPedidos dialog = new frmTablaPedidos(null, true);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
           */ 
            tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
                            ComunicacionBD.datosBD(tabla),datosTabla));
        } catch (SQLException ex) {
            Logger.getLogger(frmTablaPedidos.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        lblSalirMouseClicked(evt);
        
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
        panSalir.setBackground(Color.red);
        lblSalir.setForeground(Color.white);
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        panSalir.setBackground(Color.white);
        lblSalir.setForeground(Color.black);
    }//GEN-LAST:event_lblSalirMouseExited

    private void jrbProveedor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbProveedor1MouseClicked

    }//GEN-LAST:event_jrbProveedor1MouseClicked

    private void jrbProveedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbProveedor1ActionPerformed

    }//GEN-LAST:event_jrbProveedor1ActionPerformed

    private void jrbProveedor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbProveedor2MouseClicked

    }//GEN-LAST:event_jrbProveedor2MouseClicked

           
    /**
     * @param args the command line arguments
    */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList datosPedido = null;
                frmDatos dialog = new frmDatos(new javax.swing.JFrame(), true, ArrayList datosPedido);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        //</editor-fold>

        /* Create and display the dialog 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList datosPedido = null;
                frmDatos dialog = new frmDatos(new javax.swing.JFrame(), true, ArrayList datosPedido);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox cbxSucursal1;
    private javax.swing.JCheckBox cbxSucursal2;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JRadioButton jrbProveedor1;
    private javax.swing.JRadioButton jrbProveedor2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblSucursal;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panFondo;
    private javax.swing.JPanel panSalir;
    private javax.swing.ButtonGroup proveedores;
    private javax.swing.ButtonGroup sucursales;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
